import { NikkeCharacter } from "./types";

// Fandom 이미지 URL 매핑 (우선)
const fandomImageMap: Record<string, string> = {
  "Anis: Sparkling Summer": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/e/ea/Anis_Sparkling_Summer_MI.png/revision/latest/scale-to-width-down/224",
  "Snow White: Heavy Arms": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/a8/Snow_White_Heavy_Arms_MI.png/revision/latest/scale-to-width-down/200",
  "Brid: Silent Track": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/7/72/Brid_Silent_Track_MI.png/revision/latest/scale-to-width-down/220",
  "Diesel: Winter Sweets": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/3b/Diesel_Winter_Sweets_MI.png/revision/latest/scale-to-width-down/223",
  "Soline: Frost Ticket": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/1/1c/Soline_Frost_Ticket_MI.png/revision/latest/scale-to-width-down/214",
  "Nayuta": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/1/19/Nayuta_MI.png/revision/latest/scale-to-width-down/200",
  "Chime": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/3b/Chime_MI.png/revision/latest/scale-to-width-down/200",
  "Jill Valentine": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/9/91/Jill_Valentine_MI.png/revision/latest/scale-to-width-down/222",
  "Ada Wong": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/4b/Ada_Wong_MI.png/revision/latest/scale-to-width-down/221",
  "Milk: Blooming Bunny": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/5b/Milk_Blooming_Bunny_MI.png/revision/latest/scale-to-width-down/200",
  "Ade: Agent Bunny": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/0/02/Ade_Agent_Bunny_MI.png/revision/latest/scale-to-width-down/200",
  "Elegg: Boom and Shock": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/45/Elegg_Boom_and_Shock_MI.png/revision/latest/scale-to-width-down/212",
  "Dorothy: Serendipity": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/f1/Dorothy_Serendipity_MI.png/revision/latest/scale-to-width-down/201",
  "Sora": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/7/7c/Sora_MI.png/revision/latest/scale-to-width-down/227",
  "Raven": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/0/02/Raven_MI.png/revision/latest/scale-to-width-down/214",
  "Arcana": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/8b/Arcana_MI.png/revision/latest/scale-to-width-down/215",
  "Mihara: Bonding Chain": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/86/Mihara_Bonding_Chain_MI.png/revision/latest/scale-to-width-down/219",
  "Little Mermaid": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/44/Little_Mermaid_MI.png/revision/latest/scale-to-width-down/208",
  "Mori": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/9/9b/Mori_MI.png/revision/latest/scale-to-width-down/203",
  "Trina": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/fa/Trina_MI.png/revision/latest/scale-to-width-down/200",
  "Asuka: WILLE": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/3f/Asuka_WILLE_MI.png/revision/latest/scale-to-width-down/225",
  "Anchor: Innocent Maid": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/1/12/Anchor_Innocent_Maid_MI.png/revision/latest/scale-to-width-down/200",
  "Mast: Romantic Maid": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/22/Mast_Romantic_Maid_MI.png/revision/latest/scale-to-width-down/200",
  "Mana": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/3f/Mana_MI.png/revision/latest/scale-to-width-down/216",
  "Rapi: Red Hood": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/c/c5/Rapi_Red_Hood_MI.png/revision/latest/scale-to-width-down/204",
  "Guillotine: Winter Slayer": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/8c/Guillotine_Winter_Slayer_MI.png/revision/latest/scale-to-width-down/201",
  "Maiden: Ice Rose": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/24/Maiden_Ice_Rose_MI.png/revision/latest/scale-to-width-down/203",
  "Flora": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/d/dd/Flora_MI.png/revision/latest/scale-to-width-down/200",
  "Grave": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/8a/Grave_MI.png/revision/latest/scale-to-width-down/223",
  "Cinderella": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/b/b2/Cinderella_MI.png/revision/latest/scale-to-width-down/219",
  "Rapunzel: Pure Grace": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/b/b7/Rapunzel_Pure_Grace_MI.png/revision/latest/scale-to-width-down/221",
  "Rumani": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/9/91/Rumani_MI.png/revision/latest/scale-to-width-down/220",
  "Phantom": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/c/c4/Phantom_MI.png/revision/latest/scale-to-width-down/200",
  "Quency: Escape Queen": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/0/07/Quency_Escape_Queen_MI.png/revision/latest/scale-to-width-down/203",
  "Ein": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/0/05/Ein_MI.png/revision/latest/scale-to-width-down/231",
  "Rosanna: Chic Ocean": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/b/b0/Rosanna_Chic_Ocean_MI.png/revision/latest/scale-to-width-down/227",
  "Sakura: Bloom in Summer": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/6/64/Sakura_Bloom_in_Summer_MI.png/revision/latest/scale-to-width-down/214",
  "Clay": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/ab/Clay_MI.png/revision/latest/scale-to-width-down/221",
  "Alice: Wonderland Bunny": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/d/d5/Alice_Wonderland_Bunny_MI.png/revision/latest/scale-to-width-down/200",
  "Soda: Twinkling Bunny": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/39/Soda_Twinkling_Bunny_MI.png/revision/latest/scale-to-width-down/200",
  "Crown": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/7/7b/Crown_MI.png/revision/latest/scale-to-width-down/200",
  "D: Killer Wife": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/c/c9/D_Killer_Wife_MI.png/revision/latest/scale-to-width-down/227",
  "Mica: Snow Buddy": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/6/6d/Mica_Snow_Buddy_MI.png/revision/latest/scale-to-width-down/225",
  "Snow White: Innocent Days": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/a7/Snow_White_Innocent_Days_MI.png/revision/latest/scale-to-width-down/200",
  "Helm: Aquamarine": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/fb/Helm_Aquamarine_MI.png/revision/latest/scale-to-width-down/200",
  "Neon: Blue Ocean": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/9/92/Neon_Blue_Ocean_MI.png/revision/latest/scale-to-width-down/220",
  "Anne: Miracle Fairy": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/8f/Anne_Miracle_Fairy_MI.png/revision/latest/scale-to-width-down/204",
  "Rupee: Winter Shopper": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/7/70/Rupee_Winter_Shopper_MI.png/revision/latest/scale-to-width-down/200",
  "Snow White": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/24/Snow_White_MI.png/revision/latest/scale-to-width-down/200",
  "Rapi": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/82/Rapi_MI.png/revision/latest/scale-to-width-down/208",
  "Jackal": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/55/Jackal_MI.png/revision/latest/scale-to-width-down/214",
  "Viper": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/a4/Viper_MI.png/revision/latest/scale-to-width-down/222",
  "Yuni": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/3/3f/Yuni_MI.png/revision/latest/scale-to-width-down/227",
  "Leona": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/52/Leona_MI.png/revision/latest/scale-to-width-down/201",
  "Mary": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/e/e1/Mary_MI.png/revision/latest/scale-to-width-down/223",
  "Liter": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/c/c2/Liter_MI.png/revision/latest/scale-to-width-down/217",
  "Noise": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/b/b9/Noise_MI.png/revision/latest/scale-to-width-down/203",
  "Power": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/42/Power_MI.png/revision/latest/scale-to-width-down/200",
  "Cocoa": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/c/c1/Cocoa_MI.png/revision/latest/scale-to-width-down/200",
  "Dolla": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/6/60/Dolla_MI.png/revision/latest/scale-to-width-down/213",
  "Miranda": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/51/Miranda_MI.png/revision/latest/scale-to-width-down/213",
  "Novel": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/6/67/Novel_MI.png/revision/latest/scale-to-width-down/206",
  "Poli": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/1/11/Poli_MI.png/revision/latest/scale-to-width-down/214",
  "Tia": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/59/Tia_MI.png/revision/latest/scale-to-width-down/203",
  "Centi": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/ad/Centi_MI.png/revision/latest/scale-to-width-down/228",
  "Eunhwa": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/27/Eunhwa_MI.png/revision/latest/scale-to-width-down/207",
  "Exia": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/d/df/Exia_MI.png/revision/latest/scale-to-width-down/220",
  "Frima": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/5d/Frima_MI.png/revision/latest/scale-to-width-down/216",
  "Guilty": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/6/69/Guilty_MI.png/revision/latest/scale-to-width-down/201",
  "Hansel": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/a1/Hansel_FB.png/revision/latest/scale-to-width-down/178",
  "Helm": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/8a/Helm_MI.png/revision/latest/scale-to-width-down/202",
  "Ingrid": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/2/2f/Ingrid_FB.png/revision/latest/scale-to-width-down/215",
  "Julia": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/45/Julia_MI.png/revision/latest/scale-to-width-down/223",
  "Kilo": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/4d/Kilo_MI.png/revision/latest/scale-to-width-down/224",
  "Marciana": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/f4/Marciana_MI.png/revision/latest/scale-to-width-down/218",
  "Mast": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/c/c9/Mast_MI.png/revision/latest/scale-to-width-down/200",
  "Maxwell": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/9/9f/Maxwell_MI.png/revision/latest/scale-to-width-down/219",
  "Naga": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/f6/Naga_MI.png/revision/latest/scale-to-width-down/229",
  "Nero": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/59/Nero_MI.png/revision/latest/scale-to-width-down/208",
  "Noah": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/80/Noah_MI.png/revision/latest/scale-to-width-down/201",
  "Pinne": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/6/67/Pinne_FB.png/revision/latest/scale-to-width-down/236",
  "Rem": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/8/82/Rem_MI.png/revision/latest/scale-to-width-down/219",
  "Rosanna": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/b/b8/Rosanna_MI.png/revision/latest/scale-to-width-down/223",
  "Sakura": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/f9/Sakura_MI.png/revision/latest/scale-to-width-down/207",
  "Signal": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/f/f3/Signal_MI.png/revision/latest/scale-to-width-down/200",
  "Sin": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/4/48/Sin_MI.png/revision/latest/scale-to-width-down/200",
  "Sugar": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/a/ad/Sugar_MI.png/revision/latest/scale-to-width-down/218",
  "Yan": "https://static.wikia.nocookie.net/nikke-goddess-of-victory-international/images/5/54/Yan_MI.png/revision/latest/scale-to-width-down/226",
  // 한국어 이름 → 영어 이름 매핑 (Fandom)
  "아르카나": "Arcana",
  "크로우": "Crow",
  "도로시": "Dorothy",
  "앵커": "Anchor",
  "크라운": "Crown",
  "디": "D",
  "드레이크": "Drake",
  "엠마": "Emma",
  "은화": "Eunhwa",
  "이노우에 타키나": "2B",
  "벨벳": "Blanc",
  "레이블": "Admi",
  "브리드": "Brid",
  "센티": "Centi",
  "차임": "Chime",
  "코코아": "Cocoa",
  "돌라": "Dolla",
  "아인": "Ein",
  "일레그": "Elegg",
  "에이다 웡": "Ada Wong",
  "에이다": "Ade",
  "스노우 화이트 : 헤비암즈": "Snow White: Heavy Arms",
  "스노우 화이트": "Snow White",
  "브리드 : 사일런트 트랙": "Brid: Silent Track",
  "디젤 : 윈터 스위츠": "Diesel: Winter Sweets",
  "디젤": "Diesel",
  "솔린 : 프로스트 티켓": "Soline: Frost Ticket",
  "리버렐리오": "Anchor",
  "나유타": "Nayuta",
  "질 발렌타인": "Jill Valentine",
  "밀크 : 블루밍 바니": "Milk: Blooming Bunny",
  "에이드 : 에이전트 바니": "Ade: Agent Bunny",
  "일레그 : 붐 앤 쇼크": "Elegg: Boom and Shock",
  "도로시 : 세렌디피티": "Dorothy: Serendipity",
  "레이븐": "Raven",
  "라피": "Rapi",
  "라피 : 레드후드": "Rapi: Red Hood",
  "마스트 : 로망틱 메이드": "Mast: Romantic Maid",
  "마나": "Mana",
  "길로틴 : 윈터 슬레이어": "Guillotine: Winter Slayer",
  "메이든 : 아이스 로즈": "Maiden: Ice Rose",
  "신데렐라": "Cinderella",
  "라푼젤 : 퓨어 그레이스": "Rapunzel: Pure Grace",
  "루마니": "Rumani",
  "퀀시 : 이스케이프 퀸": "Quency: Escape Queen",
  "마리": "Mary",
  "츠바이": "Tia",
  "사쿠라 : 블룸 인 섬머": "Sakura: Bloom in Summer",
  "앨리스 : 원더랜드 바니": "Alice: Wonderland Bunny",
  "트로니": "Troni",
  "로 SANna : 시크 오션": "Rosanna: Chic Ocean",
  "클레이": "Clay",
  "D : 킬러 와이프": "D: Killer Wife",
  "프리바티": "Privaty",
  "홍련": "Hongren",
  "미카 : 스노우 버디": "Mica: Snow Buddy",
  "루드밀라": "Ludmila",
  "스노우 화이트 : 이노센트 데이즈": "Snow White: Innocent Days",
  "헬름 : 아쿠아마린": "Helm: Aquamarine",
  "네온 : 블루 오션": "Neon: Blue Ocean",
  "메어리": "Merry",
  "앤 : 미라클 페어리": "Anne: Miracle Fairy",
  "루피 : 윈터 쇼퍼": "Rupee: Winter Shopper",
  "홍련 : 흑영": "Hongren: Black Shadow",
  "이브": "Eve",
  "미하라 : 본딩 체인": "Mihara: Bonding Chain",
  "리틀 머메이드": "Little Mermaid",
  "모리": "Mori",
  "크러스트": "Kruust",
  "브래디": "Bradi",
  "트리나": "Trina",
  "레이 (가칭)": "Ray",
  "아스카 : WILLE": "Asuka: WILLE",
  "플로라": "Flora",
  "그레이브": "Grave",
  "루주": "Ruzu",
  "레이": "Ray",
  "아스카": "Asuka",
  "소다 : 트윙클링 바니": "Soda: Twinkling Bunny",
  "신디": "Sindy",
};

// dotgg.gg ID 매핑 (대체)
const dotggIdMap: Record<string, string> = {
  "2B": "c810",
  "A2": "c811",
  "Ada": "c840",
  "Ade": "c310",
  "Admi": "c172",
  "Alice": "c191",
  "Anis": "c012",
  "Anchor": "c351",
  "Biscuit": "c381",
  "Blanc": "c270",
  "Brid": "c070",
  "Crow": "c110",
  "D": "c040",
  "Delta": "c020",
  "Diesel": "c072",
  "Dorothy": "c233",
  "Drake": "c101",
  "Eunhwa": "c092",
  "Emma": "c090",
  "Elegg": "c500",
  "Arcana": "c581",
};

// 한국어 → 영어 매핑
const korToEng: Record<string, string> = {
  "이노우에 타키나": "2B",
  "니시키기 치사토": "A2",
  "벨벳": "Blanc",
  "레이블": "Admi",
  "스노우 화이트 : 헤비암즈": "Snow White: Heavy Arms",
  "브리드 : 사일런트 트랙": "Brid: Silent Track",
  "디젤 : 윈터 스위츠": "Diesel: Winter Sweets",
  "솔린 : 프로스트 티켓": "Soline: Frost Ticket",
  "리버렐리오": "Anchor",
  "나유타": "Nayuta",
  "차임": "Chime",
  "델타 : 닌자 시프": "Delta",
  "질 발렌타인": "Jill Valentine",
  "에이다 웡": "Ada Wong",
  "밀크 : 블루밍 바니": "Milk: Blooming Bunny",
  "에이드 : 에이전트 바니": "Ade: Agent Bunny",
  "일레그 : 붐 앤 쇼크": "Elegg: Boom and Shock",
  "도로시 : 세렌디피티": "Dorothy: Serendipity",
  "소라": "Sora",
  "레이븐": "Raven",
  "이브": "Eve",
  "아르카나": "Arcana",
  "미하라 : 본딩 체인": "Mihara: Bonding Chain",
  "리틀 머메이드": "Little Mermaid",
  "모리": "Mori",
  "트리나": "Trina",
  "아스카 : WILLE": "Asuka: WILLE",
  "앵커 : 이노센트 메이드": "Anchor: Innocent Maid",
  "마스트 : 로망틱 메이드": "Mast: Romantic Maid",
  "마나": "Mana",
  "라피 : 레드후드": "Rapi: Red Hood",
  "길로틴 : 윈터 슬레이어": "Guillotine: Winter Slayer",
  "메이든 : 아이스 로즈": "Maiden: Ice Rose",
  "플로라": "Flora",
  "그레이브": "Grave",
  "신데렐라": "Cinderella",
  "라푼젤 : 퓨어 그레이스": "Rapunzel: Pure Grace",
  "루마니": "Rumani",
  "팬텀": "Phantom",
  "퀀시 : 이스케이프 퀸": "Quency: Escape Queen",
  "마리": "Mary",
  "츠바이": "Tia",
  "아인": "Ein",
  "로산나 : 시크 오션": "Rosanna: Chic Ocean",
  "사쿠라 : 블룸 인 섬머": "Sakura: Bloom in Summer",
  "클레이": "Clay",
  "앨리스 : 원더랜드 바니": "Alice: Wonderland Bunny",
  "소다 : 트윙클링 바니": "Soda: Twinkling Bunny",
  "크라운": "Crown",
  "D : 킬러 와이프": "D: Killer Wife",
  "미카 : 스노우 버디": "Mica: Snow Buddy",
  "스노우 화이트 : 이노센트 데이즈": "Snow White: Innocent Days",
  "헬름 : 아쿠아마린": "Helm: Aquamarine",
  "아니스 : 스파클링 서머": "Anis: Sparkling Summer",
  "네온 : 블루 오션": "Neon: Blue Ocean",
  "앤 : 미라클 페어리": "Anne: Miracle Fairy",
  "루피 : 윈터 쇼퍼": "Rupee: Winter Shopper",
  "홍련": "Hongren",
  "스노우 화이트": "Snow White",
  "라피": "Rapi",
  "아나": "Anna",
  "유니": "Yuni",
  "레오나": "Leona",
  // 기본 이름들
  "브리드": "Brid",
  "디젤": "Diesel",
  "엠마": "Emma",
  "은화": "Eunhwa",
  "드에": "Ade",
  "일레그": "Elegg",
};

/** 이미지 URL 생성 */
export function getImageUrl(name: string): string {
  // 1. 바로 Fandom 이미지 확인
  if (fandomImageMap[name]) {
    return fandomImageMap[name];
  }

  // 2. 한국어 → 영어 변환 후 Fandom 확인
  const engName = korToEng[name];
  if (engName && fandomImageMap[engName]) {
    return fandomImageMap[engName];
  }

  // 3. dotgg.gg 이미지 (영어 → ID)
  if (dotggIdMap[name]) {
    return `https://static.dotgg.gg/nikke/characters/si_${dotggIdMap[name]}_00_s.webp`;
  }

  // 4. 한국어 → 영어 → dotgg
  if (engName && dotggIdMap[engName]) {
    return `https://static.dotgg.gg/nikke/characters/si_${dotggIdMap[engName]}_00_s.webp`;
  }

  // 5. 플레이스홀더
  return `https://placehold.co/300x400/1a1a24/ff2d6a?text=${encodeURIComponent(name)}`;
}

/** JSON 데이터 → NikkeCharacter 변환 */
function transformData(jsonData: any[]): NikkeCharacter[] {
  return jsonData.map((char, index) => {
    const id = char.name
      .replace(/\s*:\s*/g, "-")
      .replace(/\s+/g, "-")
      .toLowerCase();

    return {
      id,
      name: char.name,
      imageUrl: getImageUrl(char.name),
      skills: {
        basic: char.skills?.basic || "-",
        recommended: char.skills?.recommended || "-",
        full: char.skills?.final || "-",
      },
      overload: char.overload?.join(", ") || "-",
      cube: char.cubes?.join(", ") || "-",
      tags: [],
      notes: char.notes || "",
    };
  });
}

// 제미나이 데이터
const rawData = [
  {"name":"이노우에 타키나","cubes":["렐릭 베어","렐릭 크래시","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/7/1","recommended":"4/7/1","final":"10/10/10"},"overload":["우월코드","공격력","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"니시키기 치사토","cubes":["렐릭 베어","렐릭 크래시","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"벨벳","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","크리티컬 대미지 3","장탄 1","크리티컬 확률"],"notes":"차지 속도 증가 X"},
  {"name":"레이블","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"스노우 화이트 : 헤비암즈","cubes":["렐릭 베어","렐릭 디스트로이"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"브리드 : 사일런트 트랙","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/1/1","recommended":"7/1/1","final":"10/1/1"},"overload":[],"notes":""},
  {"name":"디젤 : 윈터 스위츠","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","차지 속도 2~4","크리티컬 확률","크리티컬 대미지","장탄"],"notes":"권장 : 차지 속도 6~7%\n종결 : 차지 속도 17%"},
  {"name":"솔린 : 프로스트 티켓","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"버스트 사용 시 \n무한 장탄"},
  {"name":"리버렐리오","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"나유타","cubes":["렐릭 베어","택티컬 어설트"],"collectible":"SR 15","skills":{"basic":"4/1/1","recommended":"7/4/4","final":"10/4/4"},"overload":[],"notes":""},
  {"name":"차임","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드","공격력","크리티컬 확률","크리티컬 대미지"],"notes":"장탄 수 증가 X"},
  {"name":"델타 : 닌자 시프","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"질 발렌타인","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 2","크리티컬 확률","크리티컬 대미지"],"notes":"0.5초 풀차지 유지"},
  {"name":"에이다 웡","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"밀크 : 블루밍 바니","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":["우월코드 4","공격력 4","차지 속도 3","장탄 1"],"notes":"장탄 옵션 4의 배수\n(5,6,7 단계)"},
  {"name":"에이드 : 에이전트 바니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"베스티 : 택티컬 업","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/9/9","final":"10/10/10"},"overload":["우월코드","공격력","장탄 2"],"notes":""},
  {"name":"은화 : 택티컬 업","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"엠마 : 택티컬 업","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 확률 1","크리티컬 대미지 2","명중률 3"],"notes":"크리티컬 or 명중 세팅"},
  {"name":"일레그 : 붐 앤 쇼크","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"도로시 : 세렌디피티","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"소라","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"크리티컬 대미지 25%\n 권장"},
  {"name":"레이븐","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"이브","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"이사벨보다 우선 육성"},
  {"name":"아르카나","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"미하라 : 본딩 체인","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"리틀 머메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"4/4/4"},"overload":[],"notes":""},
  {"name":"모리","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","차지 속도 3","장탄 1"],"notes":""},
  {"name":"크러스트","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":[],"notes":""},
  {"name":"브래디","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 2~4"],"notes":""},
  {"name":"트리나","cubes":["렐릭 퀀텀","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"레이 (가칭)","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드","공격력","장탄","차지 속도"],"notes":""},
  {"name":"아스카 : WILLE","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"앵커 : 이노센트 메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 10","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"7/9/7"},"overload":["우월코드","공격력","장탄","명중률","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"마스트 : 로망틱 메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"장탄 2줄 필수"},
  {"name":"마나","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/7","final":"7/9/9"},"overload":["우월코드 4","공격력 4","장탄 4"],"notes":""},
  {"name":"라피 : 레드후드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"9/7/9"},"overload":[],"notes":""},
  {"name":"길로틴 : 윈터 슬레이어","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"메이든 : 아이스 로즈","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR  15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"플로라","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 1~2","크리티컬 대미지","크리티컬 확률"],"notes":""},
  {"name":"그레이브","cubes":["렐릭 베어","렐릭 피어싱"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"신데렐라","cubes":["택티컬 베어","렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"7/4/7"},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"라푼젤 : 퓨어 그레이스","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"루마니","cubes":["렐릭 퀀텀","렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/9/9","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 2","명중률 2"],"notes":""},
  {"name":"팬텀","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":[],"notes":""},
  {"name":"퀀시 : 이스케이프 퀸","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/9","final":"9/9/10"},"overload":["차지 속도","장탄","공격력","우월코드"],"notes":""},
  {"name":"루주","cubes":["렐릭 베어","렐릭 부스트","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"마리","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 2~4","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"레이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"7/7/7","recommended":"10/7/10","final":"10/10/10"},"overload":[],"notes":"관통 덱 파츠"},
  {"name":"아스카","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄  2","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"츠바이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"4/4/10"},"overload":[],"notes":""},
  {"name":"아인","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":["우월코드 4","공격력 4","장탄 4"],"notes":""},
  {"name":"로산나 : 시크 오션","cubes":["렐릭 베어","택티컬 베어","택티컬 부스트"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"사쿠라 : 블룸 인 섬머","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"4/10/4"},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"클레이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":[],"notes":""},
  {"name":"앨리스 : 원더랜드 바니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"소다 : 트윙클링 바니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"트로니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"크라운","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"킬로","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":["장탄","우월코드","공격력","크리티컬 대미지"],"notes":""},
  {"name":"베이","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"2단계","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":[],"notes":"PVP 니케"},
  {"name":"에밀리아","cubes":["렐릭 베어","렐릭 부스트","택티컬 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"D : 킬러 와이프","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"일레그","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/7"},"overload":[],"notes":""},
  {"name":"에이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"4/7/7","final":"10/10/10"},"overload":["방어력(PVP)","공격력","명중률","우월코드"],"notes":""},
  {"name":"프리바티 : 언카인드 메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"목단","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"3단계","skills":{"basic":"7/7/7","recommended":"9/7/9","final":"10/7/10"},"overload":["우월코드 4","공격력 4","차지 속도 3","장탄 1"],"notes":"차지 속도 최소 4%\n장탄 50% 이상"},
  {"name":"레오나","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"홍련 : 흑영","cubes":["렐릭 베어","렐릭 부스트","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 대미지"],"notes":"토템 사용 시 버스트 1렙"},
  {"name":"미카 : 스노우 버디","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"7/4/4","recommended":"9/7/7","final":"10/10/10"},"overload":[],"notes":"샷건 덱 파츠"},
  {"name":"루드밀라 : 윈터 오너","cubes":["택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 1","차지 속도","차지 대미지"],"notes":""},
  {"name":"토브","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"레드 후드","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"스노우 화이트 : 이노센트 데이즈","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"9/4/4"},"overload":[],"notes":"나가랑 세트"},
  {"name":"키리","cubes":["렐릭 부스트","렐릭 퀀텀"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"티아","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"4/4/4"},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"나가","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"마르차나","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"2B","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"1/4/1","final":"1/9/1"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"A2","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/9"},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"헬름 : 아쿠아마린","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":["우월코드","공격력","장탄","크리티컬 확률"],"notes":""},
  {"name":"아니스 : 스파클링 서머","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/7"},"overload":[],"notes":""},
  {"name":"마스트","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"네로","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"네온 : 블루 오션","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"7/7/7","recommended":"7/9/9","final":"7/10/10"},"overload":["공격력","장탄"],"notes":"PVP 니케"},
  {"name":"메어리 : 베이 갓데스","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"10/10/4"},"overload":[],"notes":"루주 or 블랑 세트"},
  {"name":"로산나","cubes":["택티컬 베어","렐릭 템퍼링"],"collectible":"SR 5(15)","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"4/7/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"누아르","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"블랑","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"도로시","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":[],"notes":"차지 속도 8.4% 이상"},
  {"name":"라이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"앨리스","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"사쿠라","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"비스킷","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"파워","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"마키마","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"소다","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/10/10"},"overload":[],"notes":"애장품 3단계는 선택"},
  {"name":"코코아","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/4","final":"10/10/4"},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"바이퍼","cubes":["렐릭 베어","택티컬 베어"],"collectible":"2단계","skills":{"basic":"4/4/4","recommended":"7/7/4","final":"10/10/7"},"overload":[],"notes":""},
  {"name":"자칼","cubes":["렐릭 퀀텀","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"모더니아","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"앤 : 미라클 페어리","cubes":["렐릭 퀀텀","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"4/10/7"},"overload":["차지 속도","장탄","공격력","우월코드"],"notes":"PVP 니케"},
  {"name":"루피 : 윈터 쇼퍼","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"크라운+프리바티 파티에서는 \n렐릭 베어 큐브 X\nPVP : 렐릭 퀀텀 큐브"},
  {"name":"라플라스","cubes":["렐릭 퀀텀"],"collectible":"3단계","skills":{"basic":"7/4/7","recommended":"9/4/9","final":"10/4/10"},"overload":["우월코드 4","공격력 4","장탄 3","명중률 1"],"notes":"PVP 니케"},
  {"name":"헬름","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"3단계","skills":{"basic":"4/4/7","recommended":"4/7/9","final":"4/7/10"},"overload":[],"notes":""},
  {"name":"홍련","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"7/7/7"},"overload":["차지 속도","장탄"],"notes":"PVP 니케\nPVE : 렐릭 베어 큐브"},
  {"name":"스노우 화이트","cubes":["렐릭 디스트로이","렐릭 부스트","택티컬 어설트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"9/9/9"},"overload":[],"notes":""},
  {"name":"라푼젤","cubes":["렐릭 퀀텀","렐릭 템퍼링"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"5/5/5","final":"7/7/7"},"overload":["차지 속도"],"notes":""},
  {"name":"이사벨","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"노아","cubes":["렐릭 퀀텀","렐릭 인듀어","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"하란","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"7/4/7","recommended":"9/7/9","final":"10/7/10"},"overload":[],"notes":"샷건 덱 파츠"},
  {"name":"니힐리스타","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":["우월코드 4","공격력 4","장탄 1","차지 대미지 3"],"notes":"토템 사용 시\n2스킬, 버스트 1레벨"},
  {"name":"드레이크","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"맥스웰","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"은화","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"엠마","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"베스티","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"4/4/4","recommended":"5/5/5","final":"7/7/7"},"overload":[],"notes":"PVP 니케\n애장품 2단계 강화 X"},
  {"name":"리타","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/7","final":"4/10/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"센티","cubes":["렐릭 퀀텀","렐릭 부스트","렐릭 베어"],"collectible":"1단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"PVP 니케"},
  {"name":"미란다","cubes":["렐릭 베어","택티컬 베어"],"collectible":"2단계","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"4/4/10"},"overload":["장탄","명중률","우월코드","공격력"],"notes":""},
  {"name":"폴리","cubes":["렐릭 베어"],"collectible":"1단계","skills":{"basic":"4/4/1","recommended":"7/7/1","final":"10/10/1"},"overload":[],"notes":"장탄 수 증가 X\n토템"},
  {"name":"노벨","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/4/4","recommended":"1/7/7","final":"1/10/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"엑시아","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"2단계","skills":{"basic":"4/4/7","recommended":"7/7/7","final":"7/7/9"},"overload":[],"notes":""},
  {"name":"볼륨","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 1","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"노이즈","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/7/7","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"아리아","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["차지 속도","장탄","공격력","우월코드"],"notes":"비사용 애장품"},
  {"name":"율리아","cubes":["렐릭 베어","택티컬 베어"],"collectible":"2단계","skills":{"basic":"1/10/1","recommended":"4/10/4","final":"10/10/10"},"overload":[],"notes":"비사용 애장품"},
  {"name":"프림","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"3단계","skills":{"basic":"1/4/4","recommended":"1/7/7","final":"1/9/9"},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"밀크","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"3단계","skills":{"basic":"7/4/4","recommended":"7/7/4","final":"10/10/4"},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"슈가","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/4/1","recommended":"1/7/1","final":"1/10/1"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"프리바티","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"율하","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":["우월코드","공격력","장탄","차지 속도"],"notes":""},
  {"name":"애드미","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"도라","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"루피","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"메어리","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"페퍼","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"크로우","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"3단계 읽어보고 올리기\n비사용 애장품"},
  {"name":"유니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"디젤","cubes":["렐릭 베어","택티컬 베어"],"collectible":"1단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"브리드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/7/4","recommended":"4/10/4","final":"7/10/7"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"솔린","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"길로틴","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"메이든","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"폴크방","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"에피넬","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"루드밀라","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/4","final":"10/10/4"},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"시그널","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"길티","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"퀀시","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"","recommended":"","final":""},"overload":[],"notes":""},
];

export const nikkeCharacters: NikkeCharacter[] = transformData(rawData);
