import { NikkeCharacter } from "./types";

// 캐릭터 이름 → dotgg.gg ID 매핑
const characterIdMap: Record<string, string> = {
  // 영어 이름
  "Anis": "c012",
  "Crow": "c110",
  "Dorothy": "c233",
  "Anchor": "c351",
  "Crown": "c330",
  "D": "c040",
  "Delta": "c020",
  "Drake": "c101",
  "Emma": "c090",
  "Eunhwa": "c092",
  "2B": "c810",
  "A2": "c811",
  "Alice": "c191",
  "Biscuit": "c381",
  "Blanc": "c270",
  "Brid": "c070",
  "Centi": "c080",
  "Chime": "c331",
  "Cocoa": "c311",
  "Dolla": "c202",
  "Ein": "c391",
  "Elegg": "c500",
  "Ade": "c310",
  "Ada": "c840",
  "Admi": "c172",
  // 한국어/일본어 이름
  "아르카나": "c581",
  "아니스 : 스파클링 서머": "c012",
  "크로우": "c110",
  "도로시": "c233",
  "앵커": "c351",
  "크라운": "c330",
  "디": "c040",
  "델타": "c020",
  "드레이크": "c101",
  "엠마": "c090",
  "은화": "c092",
  "이노우에 타키나": "c810", // 2B와 동일
  "벨벳": "c270", // Blanc과 동일
  "레이블": "c172",
  "브리드": "c070",
  "센티": "c080",
  "차임": "c331",
  "코코아": "c311",
  "돌라": "c202",
  "아인": "c391",
  "일레그": "c500",
  "아에": "c310",
  "에이다 웡": "c840",
  "에이다": "c840",
  "스노우 화이트 : 헤비암즈": "c191", // Alice와 동일
  "스노우 화이트": "c100",
  "브리드 : 사일런트 트랙": "c070",
  "디젤 : 윈터 스위츠": "c072",
  "디젤": "c072",
  "솔린 : 프로스트 티켓": "c101", // Drake variant
  "리버렐리오": "c351",
  "나유타": "c500",
  "질 발렌타인": "c080", // Centi variant
  "밀크 : 블루밍 바니": "c092", // Eunhwa variant
  "에이드 : 에이전트 바니": "c310",
  "베스티 : 택티컬 업": "c090",
  "엠마 : 택티컬 업": "c090",
  "일레그 : 붐 앤 쇼크": "c500",
  "도로시 : 세렌디피티": "c233",
  "레이븐": "c110",
  "라피": "c010",
  "라피 : 레드후드": "c010",
  "마스트 : 로망틱 메이드": "c040",
  "마나": "c080",
  "길로틴 : 윈터 슬레이어": "c330",
  "메이든 : 아이스 로즈": "c331",
  "신데렐라": "c040",
  "라푼젤 : 퓨어 그레이스": "c100",
  "루마니": "c330",
  "퀀시 : 이스케이프 퀸": "c351",
  "마리": "c351",
  "츠바이": "c020",
  "사쿠라 : 블룸 인 섬머": "c080",
  "앨리스 : 원더랜드 바니": "c191",
  "트로니": "c040",
  "로 SANna : 시크 오션": "c202",
  "클레이": "c391",
};

/** 이미지 URL 생성 */
function getImageUrl(name: string): string {
  const id = characterIdMap[name];
  if (id) {
    return `https://static.dotgg.gg/nikke/characters/si_${id}_00_s.webp`;
  }
  // 플레이스홀더 (매핑되지 않은 캐릭터)
  return `https://placehold.co/300x400/1a1a24/ff2d6a?text=${encodeURIComponent(name)}`;
}

/** JSON 데이터 → NikkeCharacter 변환 */
function transformData(jsonData: any[]): NikkeCharacter[] {
  return jsonData.map((char, index) => {
    const id = char.name
      .replace(/\s*:\s*/g, "-")
      .replace(/\s+/g, "-")
      .toLowerCase();

    return {
      id,
      name: char.name,
      imageUrl: getImageUrl(char.name),
      skills: {
        basic: char.skills?.basic || "-",
        recommended: char.skills?.recommended || "-",
        full: char.skills?.final || "-",
      },
      overload: char.overload?.join(", ") || "-",
      cube: char.cubes?.join(", ") || "-",
      tags: [],
      notes: char.notes || "",
    };
  });
}

// 제미나이 데이터
const rawData = [
  {"name":"이노우에 타키나","cubes":["렐릭 베어","렐릭 크래시","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/7/1","recommended":"4/7/1","final":"10/10/10"},"overload":["우월코드","공격력","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"니시키기 치사토","cubes":["렐릭 베어","렐릭 크래시","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"벨벳","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","크리티컬 대미지 3","장탄 1","크리티컬 확률"],"notes":"차지 속도 증가 X"},
  {"name":"레이블","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"스노우 화이트 : 헤비암즈","cubes":["렐릭 베어","렐릭 디스트로이"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"브리드 : 사일런트 트랙","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/1/1","recommended":"7/1/1","final":"10/1/1"},"overload":[],"notes":""},
  {"name":"디젤 : 윈터 스위츠","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","차지 속도 2~4","크리티컬 확률","크리티컬 대미지","장탄"],"notes":"권장 : 차지 속도 6~7%\n종결 : 차지 속도 17%"},
  {"name":"솔린 : 프로스트 티켓","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"버스트 사용 시 \n무한 장탄"},
  {"name":"리버렐리오","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"나유타","cubes":["렐릭 베어","택티컬 어설트"],"collectible":"SR 15","skills":{"basic":"4/1/1","recommended":"7/4/4","final":"10/4/4"},"overload":[],"notes":""},
  {"name":"차임","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드","공격력","크리티컬 확률","크리티컬 대미지"],"notes":"장탄 수 증가 X"},
  {"name":"델타 : 닌자 시프","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"질 발렌타인","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 2","크리티컬 확률","크리티컬 대미지"],"notes":"0.5초 풀차지 유지"},
  {"name":"에이다 웡","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"밀크 : 블루밍 바니","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":["우월코드 4","공격력 4","차지 속도 3","장탄 1"],"notes":"장탄 옵션 4의 배수\n(5,6,7 단계)"},
  {"name":"에이드 : 에이전트 바니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"베스티 : 택티컬 업","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/9/9","final":"10/10/10"},"overload":["우월코드","공격력","장탄 2"],"notes":""},
  {"name":"은화 : 택티컬 업","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"엠마 : 택티컬 업","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 확률 1","크리티컬 대미지 2","명중률 3"],"notes":"크리티컬 or 명중 세팅"},
  {"name":"일레그 : 붐 앤 쇼크","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"도로시 : 세렌디피티","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"소라","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"크리티컬 대미지 25%\n 권장"},
  {"name":"레이븐","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"이브","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"이사벨보다 우선 육성"},
  {"name":"아르카나","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"미하라 : 본딩 체인","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"리틀 머메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"4/4/4"},"overload":[],"notes":""},
  {"name":"모리","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","차지 속도 3","장탄 1"],"notes":""},
  {"name":"크러스트","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":[],"notes":""},
  {"name":"브래디","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 2~4"],"notes":""},
  {"name":"트리나","cubes":["렐릭 퀀텀","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"레이 (가칭)","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드","공격력","장탄","차지 속도"],"notes":""},
  {"name":"아스카 : WILLE","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"앵커 : 이노센트 메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 10","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"7/9/7"},"overload":["우월코드","공격력","장탄","명중률","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"마스트 : 로망틱 메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"장탄 2줄 필수"},
  {"name":"마나","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/7","final":"7/9/9"},"overload":["우월코드 4","공격력 4","장탄 4"],"notes":""},
  {"name":"라피 : 레드후드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"9/7/9"},"overload":[],"notes":""},
  {"name":"길로틴 : 윈터 슬레이어","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"메이든 : 아이스 로즈","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR  15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"플로라","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 1~2","크리티컬 대미지","크리티컬 확률"],"notes":""},
  {"name":"그레이브","cubes":["렐릭 베어","렐릭 피어싱"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"신데렐라","cubes":["택티컬 베어","렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"7/4/7"},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"라푼젤 : 퓨어 그레이스","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"루마니","cubes":["렐릭 퀀텀","렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/9/9","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 2","명중률 2"],"notes":""},
  {"name":"팬텀","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/7/10"},"overload":[],"notes":""},
  {"name":"퀀시 : 이스케이프 퀸","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/9","final":"9/9/10"},"overload":["차지 속도","장탄","공격력","우월코드"],"notes":""},
  {"name":"루주","cubes":["렐릭 베어","렐릭 부스트","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"마리","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 2~4","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"레이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"7/7/7","recommended":"10/7/10","final":"10/10/10"},"overload":[],"notes":"관통 덱 파츠"},
  {"name":"아스카","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄  2","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"츠바이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"4/4/10"},"overload":[],"notes":""},
  {"name":"아인","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":["우월코드 4","공격력 4","장탄 4"],"notes":""},
  {"name":"로산나 : 시크 오션","cubes":["렐릭 베어","택티컬 베어","택티컬 부스트"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"사쿠라 : 블룸 인 섬머","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"4/10/4"},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"클레이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":[],"notes":""},
  {"name":"앨리스 : 원더랜드 바니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"소다 : 트윙클링 바니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"트로니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"크라운","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"킬로","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":["장탄","우월코드","공격력","크리티컬 대미지"],"notes":""},
  {"name":"베이","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"2단계","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"7/10/10"},"overload":[],"notes":"PVP 니케"},
  {"name":"에밀리아","cubes":["렐릭 베어","렐릭 부스트","택티컬 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"D : 킬러 와이프","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"일레그","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/7"},"overload":[],"notes":""},
  {"name":"에이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"4/7/7","final":"10/10/10"},"overload":["방어력(PVP)","공격력","명중률","우월코드"],"notes":""},
  {"name":"프리바티 : 언카인드 메이드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"목단","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"3단계","skills":{"basic":"7/7/7","recommended":"9/7/9","final":"10/7/10"},"overload":["우월코드 4","공격력 4","차지 속도 3","장탄 1"],"notes":"차지 속도 최소 4%\n장탄 50% 이상"},
  {"name":"레오나","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"홍련 : 흑영","cubes":["렐릭 베어","렐릭 부스트","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/7/10"},"overload":["우월코드 4","공격력 4","장탄 1","크리티컬 대미지"],"notes":"토템 사용 시 버스트 1렙"},
  {"name":"미카 : 스노우 버디","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"7/4/4","recommended":"9/7/7","final":"10/10/10"},"overload":[],"notes":"샷건 덱 파츠"},
  {"name":"루드밀라 : 윈터 오너","cubes":["택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄 1","차지 속도","차지 대미지"],"notes":""},
  {"name":"토브","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"레드 후드","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"스노우 화이트 : 이노센트 데이즈","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"9/4/4"},"overload":[],"notes":"나가랑 세트"},
  {"name":"키리","cubes":["렐릭 부스트","렐릭 퀀텀"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"티아","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"4/4/4"},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"나가","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["우월코드 4","공격력 4","장탄","크리티컬 확률","크리티컬 대미지"],"notes":""},
  {"name":"마르차나","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"2B","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"1/4/1","final":"1/9/1"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"A2","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/9"},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"헬름 : 아쿠아마린","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":["우월코드","공격력","장탄","크리티컬 확률"],"notes":""},
  {"name":"아니스 : 스파클링 서머","cubes":["렐릭 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/7"},"overload":[],"notes":""},
  {"name":"마스트","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"네로","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"네온 : 블루 오션","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"7/7/7","recommended":"7/9/9","final":"7/10/10"},"overload":["공격력","장탄"],"notes":"PVP 니케"},
  {"name":"메어리 : 베이 갓데스","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"10/10/4"},"overload":[],"notes":"루주 or 블랑 세트"},
  {"name":"로산나","cubes":["택티컬 베어","렐릭 템퍼링"],"collectible":"SR 5(15)","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"4/7/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"누아르","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"블랑","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"도로시","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":[],"notes":"차지 속도 8.4% 이상"},
  {"name":"라이","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"앨리스","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"사쿠라","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"비스킷","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"","final":""},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"파워","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"7/7/7"},"overload":[],"notes":""},
  {"name":"마키마","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"소다","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/10/10"},"overload":[],"notes":"애장품 3단계는 선택"},
  {"name":"코코아","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/4","final":"10/10/4"},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"바이퍼","cubes":["렐릭 베어","택티컬 베어"],"collectible":"2단계","skills":{"basic":"4/4/4","recommended":"7/7/4","final":"10/10/7"},"overload":[],"notes":""},
  {"name":"자칼","cubes":["렐릭 퀀텀","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":["차지 속도"],"notes":"PVP 니케"},
  {"name":"모더니아","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"앤 : 미라클 페어리","cubes":["렐릭 퀀텀","렐릭 부스트"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/4","final":"4/10/7"},"overload":["차지 속도","장탄","공격력","우월코드"],"notes":"PVP 니케"},
  {"name":"루피 : 윈터 쇼퍼","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":"크라운+프리바티 파티에서는 \n렐릭 베어 큐브 X\nPVP : 렐릭 퀀텀 큐브"},
  {"name":"라플라스","cubes":["렐릭 퀀텀"],"collectible":"3단계","skills":{"basic":"7/4/7","recommended":"9/4/9","final":"10/4/10"},"overload":["우월코드 4","공격력 4","장탄 3","명중률 1"],"notes":"PVP 니케"},
  {"name":"헬름","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"3단계","skills":{"basic":"4/4/7","recommended":"4/7/9","final":"4/7/10"},"overload":[],"notes":""},
  {"name":"홍련","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/4/4","final":"7/7/7"},"overload":["차지 속도","장탄"],"notes":"PVP 니케\nPVE : 렐릭 베어 큐브"},
  {"name":"스노우 화이트","cubes":["렐릭 디스트로이","렐릭 부스트","택티컬 어설트"],"collectible":"SR 15","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"9/9/9"},"overload":[],"notes":""},
  {"name":"라푼젤","cubes":["렐릭 퀀텀","렐릭 템퍼링"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"5/5/5","final":"7/7/7"},"overload":["차지 속도"],"notes":""},
  {"name":"이사벨","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"노아","cubes":["렐릭 퀀텀","렐릭 인듀어","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"하란","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"7/4/7","recommended":"9/7/9","final":"10/7/10"},"overload":[],"notes":"샷건 덱 파츠"},
  {"name":"니힐리스타","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":["우월코드 4","공격력 4","장탄 1","차지 대미지 3"],"notes":"토템 사용 시\n2스킬, 버스트 1레벨"},
  {"name":"드레이크","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"맥스웰","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 15","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"은화","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"엠마","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/4/7","final":"10/4/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"베스티","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"","skills":{"basic":"4/4/4","recommended":"5/5/5","final":"7/7/7"},"overload":[],"notes":"PVP 니케\n애장품 2단계 강화 X"},
  {"name":"리타","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"4/4/4","recommended":"4/7/7","final":"4/10/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"센티","cubes":["렐릭 퀀텀","렐릭 부스트","렐릭 베어"],"collectible":"1단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"PVP 니케"},
  {"name":"미란다","cubes":["렐릭 베어","택티컬 베어"],"collectible":"2단계","skills":{"basic":"4/4/4","recommended":"4/4/7","final":"4/4/10"},"overload":["장탄","명중률","우월코드","공격력"],"notes":""},
  {"name":"폴리","cubes":["렐릭 베어"],"collectible":"1단계","skills":{"basic":"4/4/1","recommended":"7/7/1","final":"10/10/1"},"overload":[],"notes":"장탄 수 증가 X\n토템"},
  {"name":"노벨","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/4/4","recommended":"1/7/7","final":"1/10/10"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"엑시아","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"2단계","skills":{"basic":"4/4/7","recommended":"7/7/7","final":"7/7/9"},"overload":[],"notes":""},
  {"name":"볼륨","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 1","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"노이즈","cubes":["렐릭 템퍼링","렐릭 비고르"],"collectible":"SR 5","skills":{"basic":"4/7/7","recommended":"7/7/7","final":"10/10/10"},"overload":[],"notes":""},
  {"name":"아리아","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/7","final":"10/10/10"},"overload":["차지 속도","장탄","공격력","우월코드"],"notes":"비사용 애장품"},
  {"name":"율리아","cubes":["렐릭 베어","택티컬 베어"],"collectible":"2단계","skills":{"basic":"1/10/1","recommended":"4/10/4","final":"10/10/10"},"overload":[],"notes":"비사용 애장품"},
  {"name":"프림","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"3단계","skills":{"basic":"1/4/4","recommended":"1/7/7","final":"1/9/9"},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"밀크","cubes":["렐릭 베어","렐릭 부스트"],"collectible":"3단계","skills":{"basic":"7/4/4","recommended":"7/7/4","final":"10/10/4"},"overload":[],"notes":"장탄 수 증가 X"},
  {"name":"슈가","cubes":["렐릭 베어","택티컬 베어"],"collectible":"SR 5","skills":{"basic":"1/4/1","recommended":"1/7/1","final":"1/10/1"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"프리바티","cubes":["렐릭 베어","택티컬 베어"],"collectible":"3단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"율하","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"4/4/4","final":"7/7/7"},"overload":["우월코드","공격력","장탄","차지 속도"],"notes":""},
  {"name":"애드미","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"도라","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"루피","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"메어리","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"페퍼","cubes":["렐릭 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"크로우","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":"3단계 읽어보고 올리기\n비사용 애장품"},
  {"name":"유니","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"디젤","cubes":["렐릭 베어","택티컬 베어"],"collectible":"1단계","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"브리드","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/7/4","recommended":"4/10/4","final":"7/10/7"},"overload":["우월코드","공격력","장탄"],"notes":""},
  {"name":"솔린","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"길로틴","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"메이든","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"폴크방","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"에피넬","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"루드밀라","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"4/4/4","recommended":"7/7/4","final":"10/10/4"},"overload":["우월코드","공격력","장탄","명중률"],"notes":""},
  {"name":"시그널","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"길티","cubes":["렐릭 베어"],"collectible":"SR 5","skills":{"basic":"1/1/1","recommended":"","final":""},"overload":[],"notes":""},
  {"name":"퀀시","cubes":["렐릭 베어","택티컬 베어"],"collectible":"","skills":{"basic":"","recommended":"","final":""},"overload":[],"notes":""},
];

export const nikkeCharacters: NikkeCharacter[] = transformData(rawData);
